### ISSUE TITLE
has_creds() uses a cached input and never resets (bad input will loop)

### ISSUE THREAD

**Issue by jasonbrackman** [anson-vandoren/esp8266-captive-portal#1]
The `captive_portal()` func has a loop that involves a call to `check_valid_wifi()` that calls a `has_creds()` function.  The has_creds() will never return None once an ssid/password is entered as it is never cleared. 

    def has_creds(self):
        self.ssid, self.password = self.http_server.saved_credentials <-- HERE
        return None not in [self.ssid, self.password]

I feel like the `connect_to_wifi()` func might be the best place to negate the cached values as you are already setting the self.ssid/self.password to None anyway?

```
...
# forget the credentials since they didn't work, and turn off station mode
self.http_server.saved_credentials = [None, None]
self.ssid = self.password = None
self.sta_if.active(False)
...
```

**Comment by anson-vandoren** [comment]
@jasonbrackman good catch, thanks! Is PR #2 what you were thinking?
