### ISSUE TITLE
No method to handle url escape characters

### ISSUE THREAD

**Issue by jlmontie** [anson-vandoren/esp8266-captive-portal#9]
Special characters are represented as url escape from the html form. For example, ! is changed %21. This change prevents connecting to my wifi. I tried to correct this with urllib.parse.unquote, but that method used a particular string split that is not implemented in micropython, returning a NotImplemented error.

**Comment by anson-vandoren** [comment]
Hi @jlmontie, thanks for submitting this and sorry it's taken a while for me to get back to you. I took a look at Python's [unquote_to_bytes()](https://github.com/python/cpython/blob/9852cb38112a4f8d11e26c3423643ea994d5a14f/Lib/urllib/parse.py#L604) function in urllib, and implemented a stripped-down version that should take care of what you need. Please let me know if you run into any issues with it.
